spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    mongodb:
      uri: mongodb://springbucks:springbucks@localhost:27017/springbucks
  cache:
    type: redis
    cache-names: coffee
    redis:
      time-to-live: 5000
      cache-null-values: false
  redis:
    host: localhost

management:
  endpoints:
    web:
      exposure:
        include: *
